language: ruby
sudo: false
rvm:
 - 2.2.2
# - jruby
# - rbx-2

cache: bundler

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec cucumber
  - bundle exec rspec

after_script:
  - bundle exec rake send_to_codeclimate
