# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

GMAIL_DOMAIN: gmail.com
GMAIL_USERNAME: housingnotificationsystem@gmail.com
GMAIL_PORT: "587"
CELL_RANGE: A2:F
APP_URL: http://ucberkeley-housing.herokuapp.com/
CANCELLATION_SUBJECT: Someone just cancelled open house schedule!
NEW_SCHEDULE_SUBJECT: Your new open house schedule!
APP_NAME: ucberkeley-housing
CLIENT_SECRETS: client_secret.json
CREDENTIALS_PATH: google_sheet_api_credentials.yaml
TEMPLATE_SHEET_ID: 693730742
TEMPLATE_SPREADSHEET_ID: 16nnHznRUjw5LMfPxBSzMgJeRftTwA4KH70D5GQwiBUE
TEMPLATE_LINK: https://docs.google.com/spreadsheets/d/16nnHznRUjw5LMfPxBSzMgJeRftTwA4KH70D5GQwiBUE/edit#gid=693730742

development:
  GMAIL_PASSWORD: 169group15
  TESTING_ENV: true

production:
  GMAIL_PASSWORD: 169group15
  HOST: ucberkeley-housing.herokuapp.com
  TESTING_ENV: false

test:
  GMAIL_PASSWORD: 169group15
  HOST: 0.0.0.0:3000
  TEST_GUY_EMAIL_ADDR: mingu08@berkeley.edu
  TEST_GUY_NAME: min
  TESTING_ENV: true
